sudo: false
language: python
python:
- '2.7'
install:
- pip install .
- pip install coveralls
script:
- python setup.py test
- coverage run --source=mod_pbxproj setup.py test
after_success: coveralls
deploy:
  provider: pypi
  user: kronenthaler
  password:
    secure: ut9H5eN/vsU4cSgbwWUakUXtyn4FDgiBq0SPOJ2BEgFrPofH1/jJKeXMZIxb1fpXRw5ritmvpjZ0hcNytm5RXb3pLEPq2UlWrdXnHEKE1QaJWAU/wbPpyIzJmI/Fk4LcHlYfosSbxWzvs3+uPu/i5uMa4i+qVf5OQSfGhZPtlZI=
  on:
    distributions: sdist bdist_wheel
    repo: kronenthaler/mod-pbxproj
